name: Build EXE and Upload to FTP

on:
  push:
    branches:
      - main  # Змінюй, якщо твоя головна гілка інша
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --name YarossAI main.py  # Зміни "main.py" на твій файл

      - name: Upload to FTP
        uses: sebastianpopp/ftp-action@v1
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          localDir: dist
          remoteDir: /public_html/YarossAI  # Змінюй, якщо треба

      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YarossAI
          path: dist/YarossAI.exe
